### PR TITLE
Add a basic app setup

### PR DESCRIPTION
**Pull request by knownasilya**
Basically it uses browserify/watchify + babelify, along with a simple static server.

Still need to work on tests.

- [x] Basic working setup
- [ ] Add styles (postcss+css modules?)
- [ ] Add prompts
- [ ] Add tests

### CODE REVIEW

**Comment by knownasilya** [comment]
Anyone active here?

**Comment by hemanth** [comment]
Sorry, was occupied with some other challenges!

**Comment by hemanth** [comment]
We can work on the rest of the Todo items, thanks for the PR!

**Comment by hemanth** [comment]
@knownasilya Still, interested?

**Comment by knownasilya** [comment]
Yes

**Comment by hemanth** [comment]
Let me know what you are targeting :)

**Comment by knownasilya** [comment]
I'll probably remove the useless prompt and add a working test setup first.

**Pull request merged**
